import { Router } from 'express';
import authRoutes from './auth.js';
import dashboardRoutes from './dashboard.js';
import cycleRoutes from './cycles.js';
import chatRoutes from './chat.js';
import diaryRoutes from './diary.js';
import askAIRoutes from './ask-ai.js';
import healthRoutes from './health.js';
import symptomRoutes from './symptoms.js';
import hydrationRoutes from './hydration.js';
import mealRoutes from './meals.js';
import moodRoutes from './mood.js';
import sleepRoutes from './sleep.js';
import reminderRoutes from './reminders.js';
import noteRoutes from './notes.js';
import emergencyRoutes from './emergency.js';
import sosRoutes from './sos.js';
import settingsRoutes from './settings.js';
import coachRoutes from './coach.js';
import funfactsRoutes from './funfacts.js';
import ordersRoutes from './orders.js';
const router = Router();
router.use(healthRoutes);
router.use(authRoutes);
router.use(dashboardRoutes);
router.use(cycleRoutes);
router.use(chatRoutes);
router.use(diaryRoutes);
router.use(askAIRoutes);
router.use(symptomRoutes);
router.use(hydrationRoutes);
router.use(mealRoutes);
router.use(moodRoutes);
router.use(sleepRoutes);
router.use(reminderRoutes);
router.use(noteRoutes);
router.use(emergencyRoutes);
router.use(sosRoutes);
router.use(settingsRoutes);
router.use(coachRoutes);
router.use(funfactsRoutes);
router.use(ordersRoutes);
export default router;
